name: Android CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    # --- 修改点：指定具体的编译任务名，解决 Ambiguous 错误 ---
    - name: Build Leanback Release APK
      run: ./gradlew assembleLeanbackJavaRelease

    - name: Build Mobile Release APK
      run: ./gradlew assembleMobileJavaRelease
    # --------------------------------------------------

    - name: Upload Leanback APK
      uses: actions/upload-artifact@v4
      with:
        name: TVBox-Leanback-Release
        path: app/build/outputs/apk/leanback/java/release/*.apk

    - name: Upload Mobile APK
      uses: actions/upload-artifact@v4
      with:
        name: TVBox-Mobile-Release
        path: app/build/outputs/apk/mobile/java/release/*.apk
