name: Android CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    # --- 1. 编译 Leanback (电视版) ---
    - name: Build Leanback Java Universal APK
      run: ./gradlew assembleLeanbackJavaAll_abiRelease

    # --- 2. 编译 Mobile (手机版) ---
    - name: Build Mobile Java Universal APK
      run: ./gradlew assembleMobileJavaAll_abiRelease

    # --- 3. 上传 TV 版 APK ---
    - name: Upload Leanback APK
      uses: actions/upload-artifact@v4
      with:
        name: TVBox-Leanback-Universal
        path: app/build/outputs/apk/leanback/java/all_abi/release/*.apk

    # --- 4. 上传 手机版 APK ---
    - name: Upload Mobile APK
      uses: actions/upload-artifact@v4
      with:
        name: TVBox-Mobile-Universal
        path: app/build/outputs/apk/mobile/java/all_abi/release/*.apk
